name = "Aventura Vegana"
author = "Daniel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d89f7180d31a21efb4ca87c4ec2822b9d63cec716f49b407a961ce0aed7ea56"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
